// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rock_Paper_Scissors_Online.Models;

#nullable disable

namespace Rock_Paper_Scissors_Online.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330015922_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.Bet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("game_id");

                    b.Property<decimal?>("Payout")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("payout");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("TargetPlayerId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_player_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameId" }, "idx_bets_game");

                    b.HasIndex(new[] { "PlayerId" }, "idx_bets_player");

                    b.ToTable("bets", (string)null);
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.ChatMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoomId", "Timestamp" }, "idx_chat_room_time")
                        .IsDescending(false, true);

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.History", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_user_id");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("integer")
                        .HasColumnName("max_rounds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OpponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("opponent_id");

                    b.Property<int>("OpponentScore")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_score");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Waiting")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_history_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "CreatorUserId" }, "idx_history_creator");

                    b.HasIndex(new[] { "OpponentId" }, "idx_history_opponent");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.PointTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Delta")
                        .HasColumnType("bigint")
                        .HasColumnName("delta");

                    b.Property<Guid?>("HistoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("history_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_point_tx_created")
                        .IsDescending();

                    b.HasIndex(new[] { "HistoryId" }, "idx_point_tx_history");

                    b.HasIndex(new[] { "UserId" }, "idx_point_tx_user");

                    b.ToTable("Point_transactions", (string)null);
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Token" }, "idx_refresh_tokens_token");

                    b.HasIndex(new[] { "UserId" }, "idx_refresh_tokens_user");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<bool>("AllowBetting")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_betting");

                    b.Property<bool>("AllowSpectators")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_spectators");

                    b.Property<int>("BestOfRounds")
                        .HasColumnType("integer")
                        .HasColumnName("best_of_rounds");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("")
                        .HasColumnName("created_by_display_name");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by_username");

                    b.Property<int>("CurrentPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("current_players");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer")
                        .HasColumnName("current_round");

                    b.Property<string>("GameState")
                        .HasColumnType("text")
                        .HasColumnName("game_state");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<int>("MaxSpectators")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("max_spectators");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PinCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pin_code");

                    b.Property<int>("PointsPerWin")
                        .HasColumnType("integer")
                        .HasColumnName("points_per_win");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Waiting")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TimeoutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeout_at");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_rooms_name")
                        .IsUnique();

                    b.HasIndex(new[] { "CreatedAt" }, "idx_rooms_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "CreatedBy" }, "idx_rooms_created_by");

                    b.HasIndex(new[] { "Status" }, "idx_rooms_status");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("avatar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentWinStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_win_streak");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played_at");

                    b.Property<int>("LongestWinStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_win_streak");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<long>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1000L)
                        .HasColumnName("points");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<int>("Ties")
                        .HasColumnType("integer")
                        .HasColumnName("ties");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer")
                        .HasColumnName("total_games");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "IX_Users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "IX_Users_username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.Bet", b =>
                {
                    b.HasOne("Rock_Paper_Scissors_Online.Models.Room", "Game")
                        .WithMany("Bets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_bets_rooms");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.History", b =>
                {
                    b.HasOne("Rock_Paper_Scissors_Online.Models.User", "CreatorUser")
                        .WithMany("HistoryCreatorUsers")
                        .HasForeignKey("CreatorUserId")
                        .HasConstraintName("FK_History_Users_creator");

                    b.HasOne("Rock_Paper_Scissors_Online.Models.User", "Opponent")
                        .WithMany("HistoryOpponents")
                        .HasForeignKey("OpponentId")
                        .HasConstraintName("FK_History_Users_opponent");

                    b.Navigation("CreatorUser");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.PointTransaction", b =>
                {
                    b.HasOne("Rock_Paper_Scissors_Online.Models.History", "History")
                        .WithMany("PointTransactions")
                        .HasForeignKey("HistoryId")
                        .HasConstraintName("FK_Point_transactions_History");

                    b.HasOne("Rock_Paper_Scissors_Online.Models.User", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Point_transactions_Users");

                    b.Navigation("History");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.RefreshToken", b =>
                {
                    b.HasOne("Rock_Paper_Scissors_Online.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_refresh_tokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.History", b =>
                {
                    b.Navigation("PointTransactions");
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.Room", b =>
                {
                    b.Navigation("Bets");
                });

            modelBuilder.Entity("Rock_Paper_Scissors_Online.Models.User", b =>
                {
                    b.Navigation("HistoryCreatorUsers");

                    b.Navigation("HistoryOpponents");

                    b.Navigation("PointTransactions");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
